name: faucet
on: [push]
jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm -e WALLET=bc1qag92pvdurn46w5uwk24mdhucpfqvv589frkvge \
                     alpine:latest \
                     sh -c "wget -qO- https://faucet.earnbtc.click/claim/$(echo $WALLET | base64 -w0)"
